// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.30.2
// source: pets/v1/pets.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPetServiceCreatePet = "/api.pets.v1.PetService/CreatePet"
const OperationPetServiceGetPet = "/api.pets.v1.PetService/GetPet"
const OperationPetServiceUpdatePet = "/api.pets.v1.PetService/UpdatePet"

type PetServiceHTTPServer interface {
	CreatePet(context.Context, *CreatePetRequest) (*CreatePetResponse, error)
	GetPet(context.Context, *GetPetRequest) (*GetPetResponse, error)
	UpdatePet(context.Context, *UpdatePetRequest) (*UpdatePetResponse, error)
}

func RegisterPetServiceHTTPServer(s *http.Server, srv PetServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/pets", _PetService_CreatePet0_HTTP_Handler(srv))
	r.PUT("/v1/pets", _PetService_UpdatePet0_HTTP_Handler(srv))
	r.GET("/v1/pets/{id}", _PetService_GetPet0_HTTP_Handler(srv))
}

func _PetService_CreatePet0_HTTP_Handler(srv PetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPetServiceCreatePet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePet(ctx, req.(*CreatePetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePetResponse)
		return ctx.Result(200, reply)
	}
}

func _PetService_UpdatePet0_HTTP_Handler(srv PetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPetServiceUpdatePet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePet(ctx, req.(*UpdatePetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePetResponse)
		return ctx.Result(200, reply)
	}
}

func _PetService_GetPet0_HTTP_Handler(srv PetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPetServiceGetPet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPet(ctx, req.(*GetPetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPetResponse)
		return ctx.Result(200, reply)
	}
}

type PetServiceHTTPClient interface {
	CreatePet(ctx context.Context, req *CreatePetRequest, opts ...http.CallOption) (rsp *CreatePetResponse, err error)
	GetPet(ctx context.Context, req *GetPetRequest, opts ...http.CallOption) (rsp *GetPetResponse, err error)
	UpdatePet(ctx context.Context, req *UpdatePetRequest, opts ...http.CallOption) (rsp *UpdatePetResponse, err error)
}

type PetServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPetServiceHTTPClient(client *http.Client) PetServiceHTTPClient {
	return &PetServiceHTTPClientImpl{client}
}

func (c *PetServiceHTTPClientImpl) CreatePet(ctx context.Context, in *CreatePetRequest, opts ...http.CallOption) (*CreatePetResponse, error) {
	var out CreatePetResponse
	pattern := "/v1/pets"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPetServiceCreatePet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PetServiceHTTPClientImpl) GetPet(ctx context.Context, in *GetPetRequest, opts ...http.CallOption) (*GetPetResponse, error) {
	var out GetPetResponse
	pattern := "/v1/pets/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPetServiceGetPet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PetServiceHTTPClientImpl) UpdatePet(ctx context.Context, in *UpdatePetRequest, opts ...http.CallOption) (*UpdatePetResponse, error) {
	var out UpdatePetResponse
	pattern := "/v1/pets"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPetServiceUpdatePet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
