// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pets/v1/pets.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Species       string                 `protobuf:"bytes,2,opt,name=species,proto3" json:"species,omitempty"`
	Breed         string                 `protobuf:"bytes,3,opt,name=breed,proto3" json:"breed,omitempty"`
	Weight        float32                `protobuf:"fixed32,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePetRequest) Reset() {
	*x = CreatePetRequest{}
	mi := &file_pets_v1_pets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetRequest) ProtoMessage() {}

func (x *CreatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pets_v1_pets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetRequest.ProtoReflect.Descriptor instead.
func (*CreatePetRequest) Descriptor() ([]byte, []int) {
	return file_pets_v1_pets_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePetRequest) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *CreatePetRequest) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *CreatePetRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreatePetRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreatePetRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

type CreatePetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePetResponse) Reset() {
	*x = CreatePetResponse{}
	mi := &file_pets_v1_pets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetResponse) ProtoMessage() {}

func (x *CreatePetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pets_v1_pets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetResponse.ProtoReflect.Descriptor instead.
func (*CreatePetResponse) Descriptor() ([]byte, []int) {
	return file_pets_v1_pets_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdatePetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePetRequest) Reset() {
	*x = UpdatePetRequest{}
	mi := &file_pets_v1_pets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetRequest) ProtoMessage() {}

func (x *UpdatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pets_v1_pets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetRequest.ProtoReflect.Descriptor instead.
func (*UpdatePetRequest) Descriptor() ([]byte, []int) {
	return file_pets_v1_pets_proto_rawDescGZIP(), []int{2}
}

type UpdatePetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePetResponse) Reset() {
	*x = UpdatePetResponse{}
	mi := &file_pets_v1_pets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetResponse) ProtoMessage() {}

func (x *UpdatePetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pets_v1_pets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetResponse.ProtoReflect.Descriptor instead.
func (*UpdatePetResponse) Descriptor() ([]byte, []int) {
	return file_pets_v1_pets_proto_rawDescGZIP(), []int{3}
}

type DeletePetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePetRequest) Reset() {
	*x = DeletePetRequest{}
	mi := &file_pets_v1_pets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePetRequest) ProtoMessage() {}

func (x *DeletePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pets_v1_pets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePetRequest.ProtoReflect.Descriptor instead.
func (*DeletePetRequest) Descriptor() ([]byte, []int) {
	return file_pets_v1_pets_proto_rawDescGZIP(), []int{4}
}

type DeletePetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePetResponse) Reset() {
	*x = DeletePetResponse{}
	mi := &file_pets_v1_pets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePetResponse) ProtoMessage() {}

func (x *DeletePetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pets_v1_pets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePetResponse.ProtoReflect.Descriptor instead.
func (*DeletePetResponse) Descriptor() ([]byte, []int) {
	return file_pets_v1_pets_proto_rawDescGZIP(), []int{5}
}

type GetPetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetRequest) Reset() {
	*x = GetPetRequest{}
	mi := &file_pets_v1_pets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetRequest) ProtoMessage() {}

func (x *GetPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pets_v1_pets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetRequest.ProtoReflect.Descriptor instead.
func (*GetPetRequest) Descriptor() ([]byte, []int) {
	return file_pets_v1_pets_proto_rawDescGZIP(), []int{6}
}

func (x *GetPetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetResponse) Reset() {
	*x = GetPetResponse{}
	mi := &file_pets_v1_pets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetResponse) ProtoMessage() {}

func (x *GetPetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pets_v1_pets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetResponse.ProtoReflect.Descriptor instead.
func (*GetPetResponse) Descriptor() ([]byte, []int) {
	return file_pets_v1_pets_proto_rawDescGZIP(), []int{7}
}

func (x *GetPetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListPetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetRequest) Reset() {
	*x = ListPetRequest{}
	mi := &file_pets_v1_pets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetRequest) ProtoMessage() {}

func (x *ListPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pets_v1_pets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetRequest.ProtoReflect.Descriptor instead.
func (*ListPetRequest) Descriptor() ([]byte, []int) {
	return file_pets_v1_pets_proto_rawDescGZIP(), []int{8}
}

type ListPetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetResponse) Reset() {
	*x = ListPetResponse{}
	mi := &file_pets_v1_pets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetResponse) ProtoMessage() {}

func (x *ListPetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pets_v1_pets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetResponse.ProtoReflect.Descriptor instead.
func (*ListPetResponse) Descriptor() ([]byte, []int) {
	return file_pets_v1_pets_proto_rawDescGZIP(), []int{9}
}

var File_pets_v1_pets_proto protoreflect.FileDescriptor

const file_pets_v1_pets_proto_rawDesc = "" +
	"\n" +
	"\x12pets/v1/pets.proto\x12\vapi.pets.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x01\n" +
	"\x10CreatePetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aspecies\x18\x02 \x01(\tR\aspecies\x12\x14\n" +
	"\x05breed\x18\x03 \x01(\tR\x05breed\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x02R\x06weight\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12>\n" +
	"\rdate_of_birth\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\"7\n" +
	"\x11CreatePetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x12\n" +
	"\x10UpdatePetRequest\"\x13\n" +
	"\x11UpdatePetResponse\"\x12\n" +
	"\x10DeletePetRequest\"\x13\n" +
	"\x11DeletePetResponse\"\x1f\n" +
	"\rGetPetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x0eGetPetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x10\n" +
	"\x0eListPetRequest\"\x11\n" +
	"\x0fListPetResponse2\xba\x03\n" +
	"\n" +
	"PetService\x12_\n" +
	"\tCreatePet\x12\x1d.api.pets.v1.CreatePetRequest\x1a\x1e.api.pets.v1.CreatePetResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/pets\x12_\n" +
	"\tUpdatePet\x12\x1d.api.pets.v1.UpdatePetRequest\x1a\x1e.api.pets.v1.UpdatePetResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\x1a\b/v1/pets\x12J\n" +
	"\tDeletePet\x12\x1d.api.pets.v1.DeletePetRequest\x1a\x1e.api.pets.v1.DeletePetResponse\x12X\n" +
	"\x06GetPet\x12\x1a.api.pets.v1.GetPetRequest\x1a\x1b.api.pets.v1.GetPetResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/pets/{id}\x12D\n" +
	"\aListPet\x12\x1b.api.pets.v1.ListPetRequest\x1a\x1c.api.pets.v1.ListPetResponseBD\n" +
	"\vapi.pets.v1P\x01Z3github.com/pawverse/pawcare-profiles/api/pets/v1;v1b\x06proto3"

var (
	file_pets_v1_pets_proto_rawDescOnce sync.Once
	file_pets_v1_pets_proto_rawDescData []byte
)

func file_pets_v1_pets_proto_rawDescGZIP() []byte {
	file_pets_v1_pets_proto_rawDescOnce.Do(func() {
		file_pets_v1_pets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pets_v1_pets_proto_rawDesc), len(file_pets_v1_pets_proto_rawDesc)))
	})
	return file_pets_v1_pets_proto_rawDescData
}

var file_pets_v1_pets_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pets_v1_pets_proto_goTypes = []any{
	(*CreatePetRequest)(nil),      // 0: api.pets.v1.CreatePetRequest
	(*CreatePetResponse)(nil),     // 1: api.pets.v1.CreatePetResponse
	(*UpdatePetRequest)(nil),      // 2: api.pets.v1.UpdatePetRequest
	(*UpdatePetResponse)(nil),     // 3: api.pets.v1.UpdatePetResponse
	(*DeletePetRequest)(nil),      // 4: api.pets.v1.DeletePetRequest
	(*DeletePetResponse)(nil),     // 5: api.pets.v1.DeletePetResponse
	(*GetPetRequest)(nil),         // 6: api.pets.v1.GetPetRequest
	(*GetPetResponse)(nil),        // 7: api.pets.v1.GetPetResponse
	(*ListPetRequest)(nil),        // 8: api.pets.v1.ListPetRequest
	(*ListPetResponse)(nil),       // 9: api.pets.v1.ListPetResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_pets_v1_pets_proto_depIdxs = []int32{
	10, // 0: api.pets.v1.CreatePetRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	0,  // 1: api.pets.v1.PetService.CreatePet:input_type -> api.pets.v1.CreatePetRequest
	2,  // 2: api.pets.v1.PetService.UpdatePet:input_type -> api.pets.v1.UpdatePetRequest
	4,  // 3: api.pets.v1.PetService.DeletePet:input_type -> api.pets.v1.DeletePetRequest
	6,  // 4: api.pets.v1.PetService.GetPet:input_type -> api.pets.v1.GetPetRequest
	8,  // 5: api.pets.v1.PetService.ListPet:input_type -> api.pets.v1.ListPetRequest
	1,  // 6: api.pets.v1.PetService.CreatePet:output_type -> api.pets.v1.CreatePetResponse
	3,  // 7: api.pets.v1.PetService.UpdatePet:output_type -> api.pets.v1.UpdatePetResponse
	5,  // 8: api.pets.v1.PetService.DeletePet:output_type -> api.pets.v1.DeletePetResponse
	7,  // 9: api.pets.v1.PetService.GetPet:output_type -> api.pets.v1.GetPetResponse
	9,  // 10: api.pets.v1.PetService.ListPet:output_type -> api.pets.v1.ListPetResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pets_v1_pets_proto_init() }
func file_pets_v1_pets_proto_init() {
	if File_pets_v1_pets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pets_v1_pets_proto_rawDesc), len(file_pets_v1_pets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pets_v1_pets_proto_goTypes,
		DependencyIndexes: file_pets_v1_pets_proto_depIdxs,
		MessageInfos:      file_pets_v1_pets_proto_msgTypes,
	}.Build()
	File_pets_v1_pets_proto = out.File
	file_pets_v1_pets_proto_goTypes = nil
	file_pets_v1_pets_proto_depIdxs = nil
}
