server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    host: ${DATABASE_HOST:mongo}
    port: ${DATABASE_PORT:27017}
    name: ${DATABASE_NAME:profiles}
