// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/pawverse/pawcare-profiles/internal/biz"
	"github.com/pawverse/pawcare-profiles/internal/conf"
	"github.com/pawverse/pawcare-profiles/internal/data"
	"github.com/pawverse/pawcare-profiles/internal/server"
	"github.com/pawverse/pawcare-profiles/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(contextContext context.Context, confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(contextContext, confData, logger)
	if err != nil {
		return nil, nil, err
	}
	iOwnerRepository := data.NewOwnerRepo(dataData)
	ownerUsecase := biz.NewOwnerUsecase(iOwnerRepository, logger)
	ownerService := service.NewOwnerService(ownerUsecase)
	grpcServer := server.NewGRPCServer(confServer, ownerService, logger)
	httpServer := server.NewHTTPServer(confServer, ownerService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
