// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.30.2
// source: owners/v1/owner.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOwnerServiceCreateOwner = "/api.owners.v1.OwnerService/CreateOwner"
const OperationOwnerServiceGetOwner = "/api.owners.v1.OwnerService/GetOwner"

type OwnerServiceHTTPServer interface {
	CreateOwner(context.Context, *CreateOwnerRequest) (*CreateOwnerResponse, error)
	GetOwner(context.Context, *emptypb.Empty) (*GetOwnerResponse, error)
}

func RegisterOwnerServiceHTTPServer(s *http.Server, srv OwnerServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/owners", _OwnerService_CreateOwner0_HTTP_Handler(srv))
	r.GET("/api/v1/owners", _OwnerService_GetOwner0_HTTP_Handler(srv))
}

func _OwnerService_CreateOwner0_HTTP_Handler(srv OwnerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateOwnerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOwnerServiceCreateOwner)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOwner(ctx, req.(*CreateOwnerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateOwnerResponse)
		return ctx.Result(200, reply)
	}
}

func _OwnerService_GetOwner0_HTTP_Handler(srv OwnerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOwnerServiceGetOwner)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOwner(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOwnerResponse)
		return ctx.Result(200, reply)
	}
}

type OwnerServiceHTTPClient interface {
	CreateOwner(ctx context.Context, req *CreateOwnerRequest, opts ...http.CallOption) (rsp *CreateOwnerResponse, err error)
	GetOwner(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *GetOwnerResponse, err error)
}

type OwnerServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOwnerServiceHTTPClient(client *http.Client) OwnerServiceHTTPClient {
	return &OwnerServiceHTTPClientImpl{client}
}

func (c *OwnerServiceHTTPClientImpl) CreateOwner(ctx context.Context, in *CreateOwnerRequest, opts ...http.CallOption) (*CreateOwnerResponse, error) {
	var out CreateOwnerResponse
	pattern := "/api/v1/owners"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOwnerServiceCreateOwner))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OwnerServiceHTTPClientImpl) GetOwner(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*GetOwnerResponse, error) {
	var out GetOwnerResponse
	pattern := "/api/v1/owners"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOwnerServiceGetOwner))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
