// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: owners/v1/owner.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOwnerRequest) Reset() {
	*x = CreateOwnerRequest{}
	mi := &file_owners_v1_owner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOwnerRequest) ProtoMessage() {}

func (x *CreateOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owners_v1_owner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOwnerRequest.ProtoReflect.Descriptor instead.
func (*CreateOwnerRequest) Descriptor() ([]byte, []int) {
	return file_owners_v1_owner_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOwnerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOwnerRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

type CreateOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOwnerResponse) Reset() {
	*x = CreateOwnerResponse{}
	mi := &file_owners_v1_owner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOwnerResponse) ProtoMessage() {}

func (x *CreateOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owners_v1_owner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOwnerResponse.ProtoReflect.Descriptor instead.
func (*CreateOwnerResponse) Descriptor() ([]byte, []int) {
	return file_owners_v1_owner_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOwnerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOwnerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOwnerResponse) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

type UpdateOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOwnerRequest) Reset() {
	*x = UpdateOwnerRequest{}
	mi := &file_owners_v1_owner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOwnerRequest) ProtoMessage() {}

func (x *UpdateOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owners_v1_owner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOwnerRequest.ProtoReflect.Descriptor instead.
func (*UpdateOwnerRequest) Descriptor() ([]byte, []int) {
	return file_owners_v1_owner_proto_rawDescGZIP(), []int{2}
}

type UpdateOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOwnerResponse) Reset() {
	*x = UpdateOwnerResponse{}
	mi := &file_owners_v1_owner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOwnerResponse) ProtoMessage() {}

func (x *UpdateOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owners_v1_owner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOwnerResponse.ProtoReflect.Descriptor instead.
func (*UpdateOwnerResponse) Descriptor() ([]byte, []int) {
	return file_owners_v1_owner_proto_rawDescGZIP(), []int{3}
}

type DeleteOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOwnerRequest) Reset() {
	*x = DeleteOwnerRequest{}
	mi := &file_owners_v1_owner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOwnerRequest) ProtoMessage() {}

func (x *DeleteOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owners_v1_owner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOwnerRequest.ProtoReflect.Descriptor instead.
func (*DeleteOwnerRequest) Descriptor() ([]byte, []int) {
	return file_owners_v1_owner_proto_rawDescGZIP(), []int{4}
}

type DeleteOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOwnerResponse) Reset() {
	*x = DeleteOwnerResponse{}
	mi := &file_owners_v1_owner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOwnerResponse) ProtoMessage() {}

func (x *DeleteOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owners_v1_owner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOwnerResponse.ProtoReflect.Descriptor instead.
func (*DeleteOwnerResponse) Descriptor() ([]byte, []int) {
	return file_owners_v1_owner_proto_rawDescGZIP(), []int{5}
}

type GetOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOwnerResponse) Reset() {
	*x = GetOwnerResponse{}
	mi := &file_owners_v1_owner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnerResponse) ProtoMessage() {}

func (x *GetOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owners_v1_owner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnerResponse.ProtoReflect.Descriptor instead.
func (*GetOwnerResponse) Descriptor() ([]byte, []int) {
	return file_owners_v1_owner_proto_rawDescGZIP(), []int{6}
}

type ListOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOwnerRequest) Reset() {
	*x = ListOwnerRequest{}
	mi := &file_owners_v1_owner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnerRequest) ProtoMessage() {}

func (x *ListOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_owners_v1_owner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnerRequest.ProtoReflect.Descriptor instead.
func (*ListOwnerRequest) Descriptor() ([]byte, []int) {
	return file_owners_v1_owner_proto_rawDescGZIP(), []int{7}
}

type ListOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOwnerResponse) Reset() {
	*x = ListOwnerResponse{}
	mi := &file_owners_v1_owner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnerResponse) ProtoMessage() {}

func (x *ListOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_owners_v1_owner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnerResponse.ProtoReflect.Descriptor instead.
func (*ListOwnerResponse) Descriptor() ([]byte, []int) {
	return file_owners_v1_owner_proto_rawDescGZIP(), []int{8}
}

var File_owners_v1_owner_proto protoreflect.FileDescriptor

const file_owners_v1_owner_proto_rawDesc = "" +
	"\n" +
	"\x15owners/v1/owner.proto\x12\rapi.owners.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"h\n" +
	"\x12CreateOwnerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\rdate_of_birth\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\"y\n" +
	"\x13CreateOwnerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12>\n" +
	"\rdate_of_birth\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\"\x14\n" +
	"\x12UpdateOwnerRequest\"\x15\n" +
	"\x13UpdateOwnerResponse\"\x14\n" +
	"\x12DeleteOwnerRequest\"\x15\n" +
	"\x13DeleteOwnerResponse\"\x12\n" +
	"\x10GetOwnerResponse\"\x12\n" +
	"\x10ListOwnerRequest\"\x13\n" +
	"\x11ListOwnerResponse2\x88\x03\n" +
	"\fOwnerService\x12o\n" +
	"\vCreateOwner\x12!.api.owners.v1.CreateOwnerRequest\x1a\".api.owners.v1.CreateOwnerResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/owners\x12T\n" +
	"\vUpdateOwner\x12!.api.owners.v1.UpdateOwnerRequest\x1a\".api.owners.v1.UpdateOwnerResponse\x12T\n" +
	"\vDeleteOwner\x12!.api.owners.v1.DeleteOwnerRequest\x1a\".api.owners.v1.DeleteOwnerResponse\x12[\n" +
	"\bGetOwner\x12\x16.google.protobuf.Empty\x1a\x1f.api.owners.v1.GetOwnerResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/ownersBH\n" +
	"\rapi.owners.v1P\x01Z5github.com/pawverse/pawcare-profiles/api/owners/v1;v1b\x06proto3"

var (
	file_owners_v1_owner_proto_rawDescOnce sync.Once
	file_owners_v1_owner_proto_rawDescData []byte
)

func file_owners_v1_owner_proto_rawDescGZIP() []byte {
	file_owners_v1_owner_proto_rawDescOnce.Do(func() {
		file_owners_v1_owner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_owners_v1_owner_proto_rawDesc), len(file_owners_v1_owner_proto_rawDesc)))
	})
	return file_owners_v1_owner_proto_rawDescData
}

var file_owners_v1_owner_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_owners_v1_owner_proto_goTypes = []any{
	(*CreateOwnerRequest)(nil),    // 0: api.owners.v1.CreateOwnerRequest
	(*CreateOwnerResponse)(nil),   // 1: api.owners.v1.CreateOwnerResponse
	(*UpdateOwnerRequest)(nil),    // 2: api.owners.v1.UpdateOwnerRequest
	(*UpdateOwnerResponse)(nil),   // 3: api.owners.v1.UpdateOwnerResponse
	(*DeleteOwnerRequest)(nil),    // 4: api.owners.v1.DeleteOwnerRequest
	(*DeleteOwnerResponse)(nil),   // 5: api.owners.v1.DeleteOwnerResponse
	(*GetOwnerResponse)(nil),      // 6: api.owners.v1.GetOwnerResponse
	(*ListOwnerRequest)(nil),      // 7: api.owners.v1.ListOwnerRequest
	(*ListOwnerResponse)(nil),     // 8: api.owners.v1.ListOwnerResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_owners_v1_owner_proto_depIdxs = []int32{
	9,  // 0: api.owners.v1.CreateOwnerRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	9,  // 1: api.owners.v1.CreateOwnerResponse.date_of_birth:type_name -> google.protobuf.Timestamp
	0,  // 2: api.owners.v1.OwnerService.CreateOwner:input_type -> api.owners.v1.CreateOwnerRequest
	2,  // 3: api.owners.v1.OwnerService.UpdateOwner:input_type -> api.owners.v1.UpdateOwnerRequest
	4,  // 4: api.owners.v1.OwnerService.DeleteOwner:input_type -> api.owners.v1.DeleteOwnerRequest
	10, // 5: api.owners.v1.OwnerService.GetOwner:input_type -> google.protobuf.Empty
	1,  // 6: api.owners.v1.OwnerService.CreateOwner:output_type -> api.owners.v1.CreateOwnerResponse
	3,  // 7: api.owners.v1.OwnerService.UpdateOwner:output_type -> api.owners.v1.UpdateOwnerResponse
	5,  // 8: api.owners.v1.OwnerService.DeleteOwner:output_type -> api.owners.v1.DeleteOwnerResponse
	6,  // 9: api.owners.v1.OwnerService.GetOwner:output_type -> api.owners.v1.GetOwnerResponse
	6,  // [6:10] is the sub-list for method output_type
	2,  // [2:6] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_owners_v1_owner_proto_init() }
func file_owners_v1_owner_proto_init() {
	if File_owners_v1_owner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_owners_v1_owner_proto_rawDesc), len(file_owners_v1_owner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_owners_v1_owner_proto_goTypes,
		DependencyIndexes: file_owners_v1_owner_proto_depIdxs,
		MessageInfos:      file_owners_v1_owner_proto_msgTypes,
	}.Build()
	File_owners_v1_owner_proto = out.File
	file_owners_v1_owner_proto_goTypes = nil
	file_owners_v1_owner_proto_depIdxs = nil
}
